### ISSUE TITLE
Cant find abbrev.bib

### ISSUE THREAD

**Issue by dinankg** [JeffFessler/bib-scripts#1]
The flag  `$keepabbrev=0 `requires a file abbrev.bib, which is not present in the bib/ folder.
Not sure what this flag does either.

**Comment by JeffFessler** [comment]
oops, sorry, i forgot to include that.  i added it now:
https://github.com/JeffFessler/bib-scripts/tree/main/data

surely some paths will need to be fixed for the scripts to find it.
the point is to be able to use short abbreviations like `ieee-spmag` in my database.
less typing and ensures consistency.
